### ISSUE TITLE
Licence information

### ISSUE THREAD

**Issue by D0g71er** [ya-isakov/vigemclient-sys#1]
Hey @ya-isakov, cool project, I should admit. I was so happy when I found as it exactly what I was looking for the my hobby project. However, it pretty frustrating that this repo is missing the license info and per [GitHub's Terms of Service](https://help.github.com/en/github/creating-cloning-and-archiving-repositories/licensing-a-repository#choosing-the-right-license):

> without a license, the default copyright laws apply, meaning that you retain all rights to your source code and no one may reproduce, distribute, or create derivative works from your work. If you're creating an open source project, we strongly encourage you to include an open source license. The Open Source Guide provides additional guidance on choosing the correct license for your project.

So could you please clarify if you want other folks (like me) to use your work and what is conditions for it by choosing the license type for this repo.
Thanks!

**Comment by ya-isakov** [comment]
Fixed, thank you!
